### ISSUE TITLE
🐛 Bug - Still dupe text

### ISSUE THREAD

**Issue by Augustus-J-Borchelt** [Valour-Software/Valour#100]
**Describe the bug**
The text that I sent is multiplied in the windows

**To Reproduce**
1. Go to 'general'
2. Click on 'the add new window then click the blank window and select the coding channel  while the other shows text in general'
3. Click the window that is in general and select coding
4. Send Message
5. See error

**Expected behavior**

**Screenshots**

**System Information:**
 - Valour Platform: [e.g. Web, Mobile App, Desktop App]
     - Browser: [e.g. chrome, safari] **Chrome
![Screenshot (143)](https://user-images.githubusercontent.com/76456793/106543915-4ba2d280-64cc-11eb-83c8-6942bf36b2ee.png)
**

**Additional context**

**Comment by brndnln** [comment]
That is the whole point of split screen chats. From your screenshots, nothing looks wrong.

**Comment by Olirules10** [comment]
This should probaly be closed.
