### ISSUE TITLE
📦 Server Discovery - Improve server discovery to find new and more servers

### ISSUE THREAD

**Issue by MrLuxuri** [Valour-Software/Valour#1008]
**Is your feature request related to a problem? Please describe.**
The valour.gg website claims to have 143 communities but on the discovery section as the image attached below, you can only see a limited number of servers, server discovery needs to improve.
![Screenshot 2023-03-29 1 49 08 PM](https://user-images.githubusercontent.com/71905307/228625662-6880352e-df9a-40bc-9f1e-83d90cd9710a.png)

**Describe the solution you'd like**
In the image I attached above, you can see a free space in the bottom right inside the server/planet discovery section, add a + sign and allow users to find more planets/servers, apart from that, a search bar to find servers would also be helpful.

**Comment by Coca162** [comment]
Server discovery is disabled by default for planets explaining the gap you see in the count, however a better discovery menu will need to be done later on (you can re-edit your issue if you wish)

**Comment by MrLuxuri** [comment]
Ahh I see, it seems like planets need to "enable" discovery to appear there, but I do wonder what will happen when you run out of space? Maybe add a scrollbar and a search bar because that is something we may have to figure it when more communites start enabling it.

**Comment by superjacobl** [comment]
A revamped discovery menu/page is currently planned for the future

**Comment by Coca162** [comment]
A new issue can be created for a revamp of server discovery, currently this one does not really suggest any ideas for it
