### ISSUE TITLE
🐛 Bug - Can't leave joined planet

### ISSUE THREAD

**Issue by MrLuxuri** [Valour-Software/Valour#1010]
**Describe the bug**
I have joined both valour.net and valour central planets, I wanted to leave valour.net, right clicked it and pressed leave server, but even after doing that, the planet I tried to leave is still listed under "your planets" which means trying to leave the planet did not work.

**To Reproduce**
Simply join a few planets, and try to leave one of em.

**Expected behavior**
When I click leave planet, I want to leave the planet and not see it under "my planets", should not remain joined when I press leave.

**Screenshots**
![Screenshot 2023-03-29 3 04 55 PM](https://user-images.githubusercontent.com/71905307/228642800-76bb9fd4-9b88-4112-b41d-fd0def5bbd0e.png)
![Screenshot 2023-03-29 3 05 08 PM](https://user-images.githubusercontent.com/71905307/228642850-a75394ba-f8f8-4eca-a668-b8fd23a7da54.png)

**System Information:**
 - ChromeOS
 - Valour Version 0.1.7.5 Pre-Alpha 
 - Valour Platform: Web
     - Chrome

**Comment by SpikeViper** [comment]
Fixed in dev
