### ISSUE TITLE
🐛 Bug - Right click menu for friending doesn't work

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#1012]
Currently the right click menu does not work for sending friend requests

![image](https://user-images.githubusercontent.com/62479942/228649563-9cb3afdb-e6f2-4c22-a177-3f3d70ac9f38.png)

### Expected behavior
A modal to confirm the if the user wants to send a friend invite as well as confirmation afterwards of it being sent

### Valour Version
Version 0.1.7.5 Pre-Alpha

**Comment by SpikeViper** [comment]
Fixed in dev
