### ISSUE TITLE
🐛 Bug - Newly created planets not appearing under "Your planets" properly

### ISSUE THREAD

**Issue by MrLuxuri** [Valour-Software/Valour#1015]
While testing, I created a test planet (the globe with the small + you see in the attached bottom image) but once I created it after inputting the title and the description, the "your planets" section did not update automatically and it did not appear immediately under "your planets". Instead, it only updated itself and showed the new planet when I manually relaunched/reloaded valour.

![Screenshot 2023-03-29 4 27 07 PM](https://user-images.githubusercontent.com/71905307/228659477-fb5b692f-44d1-42dc-8de6-ada30097ae88.png)

**Comment by Coca162** [comment]
Note this also happens when you turn on discoverability. These are both caused because of lack of updating home.

**Comment by SpikeViper** [comment]
Should be fixed
