### ISSUE TITLE
🐛 Bug - Created planets cannot be deleted properly

### ISSUE THREAD

**Issue by MrLuxuri** [Valour-Software/Valour#1021]
I created 2 planets for test purposes and then through planet/server settings, I deleted them and they disappeared from my "your planets" section, but they weren't really deleted as they reappear as soon as I reload/refresh valour. Even after trying multiple times to delete the planets, once valour is reloaded, they keep coming back.

**Comment by SpikeViper** [comment]
This is working in dev (Right click -> edit -> delete)
