### ISSUE TITLE
🐛 Bug - Deleting default general chat breaks planet

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#1023]
**Describe the bug**
When opening a planet with a deleted default channel, the UI does not open any channel. Opening other channels in the planet sometimes works (possibly after opening another planet's channels).

**To Reproduce**
1. Have a new planet
2. Delete the `General` channel
3. Close the planet
4. Observe behavior by opening planet

**Expected behavior**
Making the primary channel newcomers are directed to something configurable, with it going to the first channel on the server if it doesn't exist or you don't have any.

**Screenshots**
An image of the observed behavior
![image](https://user-images.githubusercontent.com/62479942/228997028-37f8fef5-398f-48bd-a56e-cf6f970675b5.png)

**Additional context**
This was originally found by Arsta, we don't know why they had the issue but I was able to replicate with this method. I assume it was the deletion of the `General` chat because of the lack of capitalization in the shown screenshot.

Valour Version 0.1.7.5 Pre-Alpha

**Comment by kobealbright** [comment]
It shouldn't even be possible to delete the default channel (we have a foreign key on the database) so this will have to be investigated. Probably due to changing to soft deletion.

**Comment by kobealbright** [comment]
This is the wrong GitHub account but point still stands

**Comment by SpikeViper** [comment]
Fixed in dev
