### ISSUE TITLE
🐛 Bug - Text box doesn't update "Discuss in General" unless clicked

### ISSUE THREAD

**Issue by ctr7029** [Valour-Software/Valour#1024]
**Describe the bug**
The text box shows "Type in general" for any text channel you click on other then general, instead of showing the name of the text channel. Updates after you click on the text box.

**Expected behavior**
The text box entry should change to match the channel.

**Screenshots**
<img width="575" alt="image" src="https://user-images.githubusercontent.com/26713115/229519143-edd287a3-809e-4b1f-b762-1d98571ff970.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/26713115/229519262-60dc3f91-ff27-4917-8b1d-d1575f9fe54a.png">

**System Information:**
 - OS: Windows 
 - Valour version 0.1.7.5
 - Valour Platform: Web
     - Browser: Opera GX

**Comment by ctr7029** [comment]
An update to this: it actually does update, but only once you click on the text box to force an update. It should refresh as soon as the channel is swapped to instead

**Comment by superjacobl** [comment]
Fixed in #1047
