### ISSUE TITLE
🐛 Bug - Adding more then 4 windows breaks right sidebar

### ISSUE THREAD

**Issue by ctr7029** [Valour-Software/Valour#1025]
**Describe the bug**
Adding more then 4 text windows makes the right sidebar go outside of the viewport

**To Reproduce**
1. Add as many windows as your screen real estate can handle
2. The sidebar should push off of the screen with no scroll over option

**Expected behavior**
Maybe an option to scroll sideways across tabs that are open or some sort of limiter on the number of tabs that can be opened based on screen resolution.

**Screenshots**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/26713115/229523561-406ee6b5-eed9-40c5-8553-63b814998131.png">

**System Information:**
 - OS: Windows
 - Valour Version 0.1.7.5 
 - Valour Platform: Web
     - Browser: Opera GX

**Comment by Coca162** [comment]
This has been fixed
