### ISSUE TITLE
🚸 UX - Displaying message's date

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#1031]
Currently the timestamp shown is:
![image](https://user-images.githubusercontent.com/62479942/232277105-84362a46-b165-454c-bce3-db281e3a275c.png)
however, this does not provide the date of a message for messages that are older then today. 

In the current UI we can put the date like this and have it easily work for older messages.
![image](https://user-images.githubusercontent.com/62479942/232277713-0a5047b1-ebb7-4bb3-bbde-7acc2e841b81.png)

We could also have a tooltip to display a fuller date on hover for when you need the time as well.

**Comment by superjacobl** [comment]
#1047
