### ISSUE TITLE
📦 Feature - Image Url Character Limit

### ISSUE THREAD

**Issue by Olirules10** [Valour-Software/Valour#105]
**Problem**
New planets do not support image urls that are over 255 characters.

**Solution**
Expand the character limit so images can more easily be added as planet pfps.

**Alternate Solution**
Allow users to upload photos from their devices to use as a planet pfp.

**Additional context**
Many images just taken off google have links over 255 characters long, so you would need to upload the image to imgur (or other photos upload sites) to use it.

**Comment by drop-lt** [comment]
something like reddit?

**Comment by SpikeViper** [comment]
Planet images will soon be fed through the MSP (for security reasons as well) which will fix this. Probably tomorrow.

**Comment by SpikeViper** [comment]
Fixed in 1985c4f250a319a6a2c8e59f0a918186a9befb23
