### ISSUE TITLE
🐛 Bug - List of Bugs from new channellist system

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#1079]
1. After adding a 2nd and 3rd channel to a top level category that only had 1 channel. Causes the new channels to not be live update added to category
  ![image](https://github.com/Valour-Software/Valour/assets/16181531/da2f3a42-ce87-4b00-bdd6-5717f0dc42a2)
  
 2. Can't move a category to be bwteen two other categories
 3. Moving top level categories does not live update, and has a few other weird bugs.

**Comment by SpikeViper** [comment]
Fixed in 2.1.0
