### ISSUE TITLE
🐛 Bug - Age Collection

### ISSUE THREAD

**Issue by Ryguy6001** [Valour-Software/Valour#1091]
The screen where you have to enter your birthday will not disappear after clicking Submit. 

(Not my real age because this is in the open not hidden from anyone)

https://github.com/Valour-Software/Valour/assets/72236069/e7185a4c-f77e-4190-a799-7e08be695c47

**Comment by SpikeViper** [comment]
hm perhaps a mobile issue

**Comment by Ryguy6001** [comment]
It was fixed with most recent update.
