### ISSUE TITLE
Embed images

### ISSUE THREAD

**Issue by identithree** [Valour-Software/Valour#11]

**Comment by SuprSpaceBoyGamz** [comment]
Not 100% related, but I made a variation of the logo that looks cool. And it is an image sooooo ye 

 
![favicon](https://user-images.githubusercontent.com/77362426/104382870-ea0acc00-54fc-11eb-97a2-48a068b6b90b.png)

**Comment by Olirules10** [comment]
Should probably be closed now, unless more work is planned aside from debugging.

**Comment by charmich0802** [comment]
> Should probably be closed now, unless more work is planned aside from debugging.

yeah i agree
