### ISSUE TITLE
📦 Feature - Pressing "Enter" to log in on web client

### ISSUE THREAD

**Issue by idi-moe** [Valour-Software/Valour#112]
**Is your feature request related to a problem? Please describe.**
Yes. When you press "enter" after entering your password, nothing happens.

**Describe the solution you'd like**
You press "Enter" and it logs you in

**Describe alternatives you've considered**
No alternative.

**Additional context**
Everyone else does it.

**Comment by SpikeViper** [comment]
Fixed in 0.2.1.0
