### ISSUE TITLE
📦 Feature - "Add friend" and "Send message" buttons in the profile card

### ISSUE THREAD

**Issue by BeauTheBeau** [Valour-Software/Valour#1153]
**Is your feature request related to a problem? Please describe.**
This is simply an alternative way to using the context menu. 

**Describe the solution you'd like**
Two buttons, above the user's Headline, below their username/avatar etc. One being "Send friend request", the other "Send message". In my mockup, I coloured them according to the user's border colour (just a bit darker), but this could lead to issues with contrast between the text and background. 

**Describe alternatives you've considered**
The preexisting context menu

**Additional context**
My mockup:
![image(9)](https://github.com/Valour-Software/Valour/assets/90942493/6b5ad0b0-408a-48f1-8397-1067e652b025)
 or screenshots about the feature request here.

**Comment by SpikeViper** [comment]
This is actually in the dev branch :) yours looks prettier though so we may steal some of the style!

**Comment by SpikeViper** [comment]
Done and restyled in latest a31b6f0dbb370ba37c32e18205350a1ecf0f12e3

**Comment by SpikeViper** [comment]
you know what, that's the wrong commit

**Comment by SpikeViper** [comment]
363bffd85c8c9c999847853ca6db84824351a393

**Comment by BeauTheBeau** [comment]
very cool! <3
