### ISSUE TITLE
Channel Selection Highlighting Issue

### ISSUE THREAD

**Issue by EdenFK27** [Valour-Software/Valour#1157]
**Describe the bug**
When selecting a channel on mobile, the entire top-level parent category is highlighted.

**To Reproduce**
1. Go to any planet.
2. Tap on any channel.
4. View the error.

**Expected behavior**
Only the selected channel is supposed to be highlighted.

**Screenshots**
![Screenshot_20231109_192750_Chrome](https://github.com/Valour-Software/Valour/assets/150401861/b3d0d809-d647-4f6d-8157-64fdecc7b00a)

**System Information:**
 - OS: Android 13
 - Valour Version: v0.3.0.0 (Alpha)
 - Valour Platform: Android Web App (Through Chrome)

**Additional context**
When selecting a channel, it's top-level parent category, and all channels (including those in sub-categories) inside are highlighted as if they were pressed. This appears purely graphical.

**Comment by SpikeViper** [comment]
No longer an issue (8997873)
