### ISSUE TITLE
🐛 Bug - invite links dont work

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#121]
**Describe the bug**
title

**To Reproduce**
1. create an invite link
2. share with someone
3. "someone" will not be able to enter

**Expected behavior**
"someone be able to join the server

**Screenshots**

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web
     - Browser: Opera GX **Only answer when saying you use Web**

**Additional context**
invite links used : 

https://valour.gg/I/KKfBuRde
https://valour.gg/I/PhOLD9zG

**Comment by superjacobl** [comment]
Yes i am working on fixing invites, expect update in a day or two.

**Comment by superjacobl** [comment]
Oops did not mean to close

**Comment by superjacobl** [comment]
I made a pr for this #136
