### ISSUE TITLE
🐛 Bug - Text stuck to bottom of chat window

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#131]
**Describe the bug**
Text gets stuck to the bottom of the chat window and persists through multiple channels

**To Reproduce**
Steps to reproduce the behavior (Disclaimer: I have no Idea what happened, this might not work for you):
1. Type in some text and immediately switch channels 

**Expected behavior**
The text is supposed to clear

**Screenshots**
![Screenshot from 2021-02-03 10-43-56](https://user-images.githubusercontent.com/72150568/106780659-d4755780-660d-11eb-94fe-d7fe2c626b02.png)
![Screenshot from 2021-02-03 10-44-01](https://user-images.githubusercontent.com/72150568/106780662-d5a68480-660d-11eb-9f28-cae606604961.png)
![Screenshot from 2021-02-03 10-44-07](https://user-images.githubusercontent.com/72150568/106780664-d63f1b00-660d-11eb-8ade-0670872e5666.png)
![Screenshot from 2021-02-03 10-44-10](https://user-images.githubusercontent.com/72150568/106780667-d63f1b00-660d-11eb-9077-d64f33fdff7c.png)

**System Information:**
 - OS: Linux (Ubuntu)
 - Valour Platform: Web
     - Browser: Chrome

**Additional context**
This may not work every time.

**Comment by superjacobl** [comment]
What version are you on?

**Comment by Snails-Of-Wrath** [comment]
> What version are you on?

The font is too small to read clearly. I think it says 0.0.6.4
I also can't replicate it anymore.

**Comment by Snails-Of-Wrath** [comment]
I'm on 0.0.6.2 and I just experienced this bug again.

**Comment by superjacobl** [comment]
If you get the wrong version (Should be 0.0.6.4 or higher rn) then do the following:
- Open dev tools in browser (F12)
- Go into Application tab
- Click Service Workers
- Unregister the service workers
- Refresh

**Comment by superjacobl** [comment]
Anyways this issue is now fixed in the most recent version.
