### ISSUE TITLE
📦 Feature - Small design changes

### ISSUE THREAD

**Issue by phanski33** [Valour-Software/Valour#133]
**Is your feature request related to a problem? Please describe.**
The small issues with design are quite annoying as every time I look at them they just dont look _right_.
It does not impact functionallity but it would be very nice to see these changes:

Issue A:
https://imgur.com/dsDrbRC

When not focused the PFPs in the user list are not centered in the bar. The valour logo in the top left is also not centered with the bar.

Issue B:
https://imgur.com/j9nnYNc

The category list leaves a large enough gap at the bottom for another channel.

**Describe the solution you'd like**
Solution for Issue A:
The area that the main window takes up is slightly decreased to widen the bar on the left, thus centering the pfps and Valour logo with the bar.

Solution for Issue B:
The free space at the bottom of categories is shortened.

**Describe alternatives you've considered**
I don;t have any alternatives.

**Additional context**
Screenshots were included with the separate issues.

**Comment by superjacobl** [comment]
The reason for the big space at the bottom of categories, is so you can drag channels/ other categories into the bottom of the category.

**Comment by NiamiTV** [comment]
Ah ok, still stands out a lot. Would it be possible for that to appear only when moving a channel/category?

**Comment by superjacobl** [comment]
Idk if theres a css thing for it, if there is, then yes it would be possiable.

**Comment by drop-lt** [comment]
> Idk if theres a css thing for it, if there is, then yes it would be possiable.

something with :focus probably would solve, but i dont know

**Comment by superjacobl** [comment]
That would cause it to do it anytime you hover over it i think

**Comment by drop-lt** [comment]
hover could cause something strange (e. g. person is grabbing the channel then it was no more space), :focus is when clicked, so porbably both at once?

**Comment by drop-lt** [comment]
:hover does that, :focus or :focus-within does it when the class or something in it is clicked, so is the one we are looking for
(porbably)

**Comment by superjacobl** [comment]
we want when its hovered over by a channel/category only

**Comment by fruitcake5** [comment]
Jacob surely you can just add a class to the category whenever a channel is bwing dragged

**Comment by superjacobl** [comment]
honk you know js, why don't you do it?

**Comment by fruitcake5** [comment]
Channel reordering is your thing

**Comment by fruitcake5** [comment]
Also someone opened a pr so its best to let them do it lmao

**Comment by Snails-Of-Wrath** [comment]
Two more things I found that fit this category.

![Screenshot (26)](https://user-images.githubusercontent.com/72150568/106825632-e45f5c80-664a-11eb-9d8a-eef4cecbef2a.png)


1. The bar horizontal at the bottom right doesn't fix the thickness of the others.
2. The username box at the top isn't aligned with the channels
