### ISSUE TITLE
🐛 Bug - passwords dont need to be the same for verification

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#139]
**Describe the bug**
passwords dont need to be the same for verification

**To Reproduce**
inconito mode:
create new acc
use some password
verify with other password
submit
done

**Expected behavior**
saying that the passwords arent the same and need to be re written

**Screenshots**

**System Information:**
 - OS: windows 10
 - Valour Platform: web
     - Browser: opera GX **Only answer when saying you use Web**

**Additional context**

**Comment by fruitcake5** [comment]
It does actually say they dont match.. before redirecting and sending an email verification code lmao

**Comment by drop-lt** [comment]
but when i did it  it just sent me to the start page

**Comment by fruitcake5** [comment]
yeah it shows for a split second

**Comment by fruitcake5** [comment]
NO I DIDNT
i hate github

**Comment by drop-lt** [comment]
bruh

**Comment by fruitcake5** [comment]
[Image](https://msp.valour.gg/1nzVFDsJCTi1ec1x2njj8d5GBNZc0djjr35648m478nfhj0) it does actually show that the passwords are incorrect, just doesnt stop the form from being submitted

**Comment by fruitcake5** [comment]
#141
