### ISSUE TITLE
🐛 Bug - Part of the text box is cut off

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#142]
**Describe the bug**
Part of the text box appears to be covered by something

**To Reproduce**
Open a new window and observe

**Screenshots**
![Screenshot (19)](https://user-images.githubusercontent.com/72150568/106823743-179fec80-6647-11eb-8726-c8ce1cea5eb1.png)

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web
     - Browser: Chrome

**Comment by Snails-Of-Wrath** [comment]
> ![Screenshot (19)](https://user-images.githubusercontent.com/72150568/106823743-179fec80-6647-11eb-8726-c8ce1cea5eb1.png)

Bottom right if you cannot find it

**Comment by fruitcake5** [comment]
part of a scroll bar

**Comment by Snails-Of-Wrath** [comment]
It only does that on the newly created window.

**Comment by fruitcake5** [comment]
Also happens when loading a planet like normal

**Comment by Snails-Of-Wrath** [comment]
> It only does that on the newly created window.

![Screenshot (21)](https://user-images.githubusercontent.com/72150568/106824061-a0b72380-6647-11eb-9dc5-71abcadbb01d.png)


> Also happens when loading a planet like normal

Yes, I forgot to mention. Thank you.

**Comment by Snails-Of-Wrath** [comment]
I found a way to fix it client-side.

1. Inspect element
2. Navigate to textbox
3. Uncheck Overflow-y

**Comment by drop-lt** [comment]
so is this done?

**Comment by superjacobl** [comment]
Yes
