### ISSUE TITLE
🐛 Bug -Recently sent messages will not appear in both windows

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#143]
**Describe the bug**
When two windows are open to the same channel, sending a message in either text box will put the message in window to the right.

**To Reproduce**
1. Open as many windows as you want.
2. Put them all in the same channel
3. Send a message

**Screenshots**
![Screenshot (24)](https://user-images.githubusercontent.com/72150568/106825083-be858800-6649-11eb-8ec5-f1de4c51161a.png)

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web
     - Browser: Chrome

**Comment by superjacobl** [comment]
What version were you on?

**Comment by Snails-Of-Wrath** [comment]
0.0.6.4, it just occurred again when I opened 3 windows.

**Comment by superjacobl** [comment]
Is this fixed @Snails-Of-Wrath?

**Comment by Snails-Of-Wrath** [comment]
Yes, closing the issue now
