### ISSUE TITLE
🐛 Bug - no keyboard

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#144]
**Describe the bug**
no keyboard on cellphone

**To Reproduce**
pwa valour
go to any channel 
notice no keyboard

**Expected behavior**
keyboard appear

**Screenshots**
![Screenshot_20210203-213013_Chrome.jpg](https://user-images.githubusercontent.com/72446297/106827294-580f6280-6667-11eb-900a-3611af6309a0.jpg)

**System Information:**
 - OS: android 10
 - Valour Platform: pwa app for mobile
     - Browser: [e.g. chrome, safari] **Only answer when saying you use Web**

**Additional context**
cellphone: samsung m30

**Comment by drop-lt** [comment]
nvm now that i noticied that the keyboard is very down the page

**Comment by drop-lt** [comment]
comment 2, somehow fixed, probably a loading problem
