### ISSUE TITLE
🐛 Bug - <small>

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#154]
**Describe the bug**
the zoom needs to be extremally big for me to create an invite

**To Reproduce**
go to a server
create an invite

**Expected behavior**
scrollbar or something

**Screenshots**

![image](https://user-images.githubusercontent.com/72446297/106943988-d66e1200-6704-11eb-8e84-376afce8a6c4.png)

**System Information:**
 - OS: windows 10
 - Valour Version: 0.0.6.42
 - Valour Platform: web
     - Browser: opera GX **Only answer when saying you use Web**

**Additional context**
Add any other context about the problem here. None

**Comment by superjacobl** [comment]
yes this is fixed in #159

**Comment by drop-lt** [comment]
ok, waiting spike now
