### ISSUE TITLE
🐛 Bug - Ability to Move and Delete Channels Clientside

### ISSUE THREAD

**Issue by Olirules10** [Valour-Software/Valour#161]
**Describe the bug**
You are able to move around the channels clientside by clicking and dragging in the navigation menu. This also occasionaly deletes the channel and you are able to make duplicates of channels as well. (all clientside however sometimes the movement of catagories stays even if you reload the page)

**To Reproduce**
1. Click on a channel in the navigation menu
2. Drag it ontop of another channel
3. It will move there, this can also delete the channel from the menu sometimes.

**Expected behavior**
The channel to either move there fine if you have perms or not be able to move the channel at all if you do not.

**Screenshots**

![image](https://user-images.githubusercontent.com/70974222/107018416-4f6a7980-6798-11eb-9c70-74b6bee6cc99.png)
![image](https://user-images.githubusercontent.com/70974222/107018970-0666f500-6799-11eb-85b6-6854c5d139e2.png)
![image](https://user-images.githubusercontent.com/70974222/107019004-0ebf3000-6799-11eb-9981-f7970f46594b.png)
![image](https://user-images.githubusercontent.com/70974222/107019021-15e63e00-6799-11eb-9b0f-bd616090a6cd.png)

**System Information:**
 - OS: Windows
 - Valour Version: 0.0.6.54
 - Valour Platform: Website/Webapp
     - Browser: Chrome

**Additional context**

**Comment by superjacobl** [comment]
This should be fixed in 0.0.6.67
