### ISSUE TITLE
🐛 Bug - <text box to the left>

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#162]
**Describe the bug**
what title says

**To Reproduce**
(what i think it is)
1. zoom out to 25% in other page
2. restart the valour tab
3. see

**Expected behavior**
saying in place

**Screenshots**
![image](https://user-images.githubusercontent.com/72446297/107048639-f276bf80-67a7-11eb-8894-1e4ee4966885.png)

**System Information:**
 - OS: windows 10
 - Valour Version 0.0.6.42
 - Valour Platform: web
     - Browser: opera GX **Only answer when saying you use Web**

**Additional context**
its just in the valour server, i restarted the page 3-5 times and the other servers were fine

**Comment by Snails-Of-Wrath** [comment]
I think this may be due to Issue #163

**Comment by drop-lt** [comment]
yea
