### ISSUE TITLE
🐛 Bug - Window sizing bug when a user sends a specific message

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#163]
**Describe the bug**
When a user send a bunch of boxes to chat, the window it's sent in becomes bigger.

**To Reproduce**
1. Have two windows open
2. Send a bunch of boxes in messages

**Expected behavior**
To loop around instead of making the window do some funky tricks

**Screenshots**
![Screenshot from 2021-02-05 09-36-02](https://user-images.githubusercontent.com/72150568/107054760-2517bc80-6796-11eb-8824-4292fce53cfb.png)

**System Information:**
 - OS: Ubuntu (Linux)
 - Valour Version 0.0.6.54
 - Valour Platform: Web
     - Browser: Chrome

**Comment by JimSkywalker** [comment]
i was unable to replicate

**Comment by SpikeViper** [comment]
This is fixed for all the message types I am aware of. Reopen if any styling breaks it.
