### ISSUE TITLE
📦 Feature - Custom Emojis

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#170]
**Is your feature request related to a problem? Please describe.**
whe dont have :pog: emoji

**Describe the solution you'd like**
:regional_indicator_{letter from a -> z}: should be something like :regional_indicator_p: should be 🅿️ (you got the idea)
:pog:, :poggers:, :pogchamp:, :orb: (more later because creativity block)

**Describe alternatives you've considered**
some emoji library?

**Additional context**

**Comment by fruitcake5** [comment]
Seems like a great way to get into a legal mess

**Comment by drop-lt** [comment]
why?

**Comment by fruitcake5** [comment]
something about making an emoji library from other peoples images without permission maybe

**Comment by drop-lt** [comment]
is it  *just* images, because i can do images if that is just the problem

**Comment by Coca162** [comment]
Close as not planned
