### ISSUE TITLE
🐛 Bug - All users are able to move channels server-side

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#171]
**Describe the bug**
All users are able to move channels server-side. It's been moving for everyone in the chat.

**To Reproduce**
1. Move a channel

**System Information:**
 - OS: Windows 10
 - Valour Version 0.0.6.67
 - Valour Platform: Web
     - Browser: Chrome

**Comment by superjacobl** [comment]
This is fixed in PR #168
