### ISSUE TITLE
📦 Feature - <mentions>

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#177]
**Is your feature request related to a problem? Please describe.**
not a problem but just an idea

**Describe the solution you'd like**
'#' means id in css,, so use to mention a channel because it is unique
so in this way
use '.' to mention categories, because css classes can be used more than once "becaus ecategories include lots of things"

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. None

**Additional context**
i know its dumb but i think its cool

**Comment by superjacobl** [comment]
done in #327
