### ISSUE TITLE
Loading screen has a harsh jump in colors

### ISSUE THREAD

**Issue by SpikeViper** [Valour-Software/Valour#18]
Because the page technically changes, the color gradient is reset. We should find a way to prevent this from happening.

Not major, but a nice thing to fix in the future.

**Comment by SuprSpaceBoyGamz** [comment]
I saw the color cycling as it should and it kept going like that for 5-10 mins then it went back to grey.

**Comment by SpikeViper** [comment]
Seems to be resolved
