### ISSUE TITLE
🐛 Bug - Client does not correctly fetch data on redirects

### ISSUE THREAD

**Issue by CleverSource** [Valour-Software/Valour#180]
**Describe the bug**
When you are redirected to a new index by the client or you do something within a modal data is not properly fetched again.

**To Reproduce**
1. Go to a planet that you own
2. Visit the planet settings
3. Click 'Invites'
4. Create an invite

**Expected behavior**
The invite should immediately appear in the 'Invite Links' section of the modal, instead you have to refresh the page, or cause the modal to reload the 'Invites' section so that you see the newly created invite.

**System Information:**
 - OS: Windows
 - Valour Version 0.0.6.696
 - Valour Platform: Web
     - Browser: Chrome 88.0.4324.146

**Additional context**
This issue is also caused when accepting an invite link; when redirected to the 'Home' page you will have to refresh the page to see the newly joined planet.

**Comment by superjacobl** [comment]
fixed in #210
