### ISSUE TITLE
🐛 Bug - Dragging category to top level duplicates category

### ISSUE THREAD

**Issue by phanski33** [Valour-Software/Valour#181]
**Describe the bug**
Dragging a category from the initial "General" category to the top level duplicates the category

**To Reproduce**
1. create a category under the initial "General" category
2. drag new category to the top level

**Expected behavior**
The category is moved and only one instance of it shows

**Screenshots**
Not able to be shown with screenshot

**System Information:**
 - OS: Windows 10
 - Valour Version 0.0.6.696
 - Valour Platform: Web
 - Browser: [e.g. chrome, safari] Chrome
     
**Additional context**
N/A

**Comment by superjacobl** [comment]
This is fixed in #210
