### ISSUE TITLE
🐛 Bug - Invites still dont work

### ISSUE THREAD

**Issue by grimtin10** [Valour-Software/Valour#188]
**Describe the bug**
Invites dont work, at all.

**To Reproduce**
1. Install desktop app
2. Click on an invite
3. See error

**Expected behavior**
It properly joining the planet and not erroring out with a 404

**Screenshots**
![issue1](https://user-images.githubusercontent.com/20334046/107290361-3c1b1080-6a1b-11eb-9ff7-27cd5921b10e.PNG)
![issue2](https://user-images.githubusercontent.com/20334046/107290367-3fae9780-6a1b-11eb-8399-32baff80ad2c.PNG)

**System Information:**
 - OS: Windows 10
 - Valour Version 0.0.6.7
 - Valour Platform: Desktop App

**Additional context**
Invites used to work, but they now just 404.

**Comment by SentyFunBall** [comment]
Same result when using mobile app, or website

**Comment by superjacobl** [comment]
what

**Comment by superjacobl** [comment]
thats impossiable, are you sure you are on the correct version?

**Comment by superjacobl** [comment]
Have you tried ctrl-f5?
