### ISSUE TITLE
🐛 Bug - Can't join planets - Invites don't work

### ISSUE THREAD

**Issue by TurtleWasTaken** [Valour-Software/Valour#192]
**Describe the bug**
When I click an invite, it gives the join confirmation, but then says: _Sorry, there's nothing at this address_

**To Reproduce**
1. Click an invite link
2. Accept the confirmation

**Expected behavior**
It should join a planet

**Screenshots**
![image](https://user-images.githubusercontent.com/62259727/107351013-054c0580-6ac2-11eb-85fb-61c1995f2a03.png)

**System Information:**
 - OS: Windows 10
 - Valour Version: 0.0.6.2
 - Valour Platform: Tried both web and desktop app
     - Browser: [e.g. chrome, safari] Google Chrome

**Comment by Mr-Turtle** [comment]
Never mind updating it fixed it

**Comment by Coca16** [comment]
Close the issue please (this is also a duplicate) @Mr-Turtle
