### ISSUE TITLE
📦 Feature - Bot API

### ISSUE THREAD

**Issue by Snails-Of-Wrath** [Valour-Software/Valour#197]
**Is your feature request related to a problem? Please describe.**
I’m a way, yes. Bots can’t really send messages without an API.

**Describe the solution you'd like**
An API needs to be made so VAPP can be used to create working bots

**Describe alternatives you've considered**
Python sending messages through Chrome but that really isn’t a good solution

**Comment by fruitcake5** [comment]
Bots can use the same api as users

**Comment by drop-lt** [comment]
but is there an easy way to do use the api / consider the account as a bot?

**Comment by SentyFunBall** [comment]
Hi yes VAPP dev here, we are currently working towards using user accounts as bots for now, hoping there will be a way to differentiate between bot and user accounts in the future. Maybe specialized tokens that will label the associated account as [BOT] or something?

**Comment by fruitcake5** [comment]
Hi yes Valour dev here, there will be ways to differentiate between user and bot accounts and probably a separate api but for now you're stuck with using c# and signalr

**Comment by fruitcake5** [comment]
Also gonna shoehorn this in

Ban selfbotting when bots have their own api and registration system

**Comment by SentyFunBall** [comment]
Tehe but they don't right now so user accounts go brrr.

**Comment by superjacobl** [comment]
Basically most of the user api will work for bots, if not all. We may add special api routes/features for bots in the future, but right now there is no plan for a separate bot api.
