### ISSUE TITLE
📦 Feature change - Configure Auto Emojis

### ISSUE THREAD

**Issue by Onyourtoes** [Valour-Software/Valour#209]
looking foward to this being fully released. can we not have auto emojis for certain things like :P or :). if we could find a way yo get around this it would be nice.

**Comment by drop-lt** [comment]
maybe, just maybe, doing something in the pipeline could work, i will try to do something....

**Comment by Coca162** [comment]
This would require changing the MarkdownPipeline on the fly which could prove to be hard
`builder.Extensions.Remove(pipeline.Extensions.Find<AutoIdentifierExtension>());` can be used to remove AutoIdentifier which are used for emojis although it may have other effects I don't know of

**Comment by Coca162** [comment]
This is now configurable per device!
