### ISSUE TITLE
🐛 Bug - Home button doesn't clear member list or planet information

### ISSUE THREAD

**Issue by fruitcake5** [Valour-Software/Valour#212]
**Describe the bug**
title

**To Reproduce**
1. Go on a planet
2. Click on the home button
3. Planet information and member list isn't cleared

**Expected behavior**
Planet information and member list is cleared 

**System Information:**
 - Valour Version Version 0.0.8.2 Pre-Pre-Alpha
 - Valour Platform: Web
     - Browser: Chrome

**Comment by superjacobl** [comment]
This is fixed
