### ISSUE TITLE
🐛 Bug - message sending lags horribly

### ISSUE THREAD

**Issue by grimtin10** [Valour-Software/Valour#215]
**Describe the bug**
After running the program for a while (>1 week) every time a message is received it lags *horribly*, taking 0.5 - 2 seconds to respond again

**To Reproduce**
1. Run Valour for a long time with an active planet open
2. Receive many messages
3. Send a message/receive a message
4. Valour should become unresponsive for ~1 second

**Expected behavior**
No lag, just smooth behavior

**Probable cause**
The debug messages in the console, when many many pile up it tends not to like it

**Screenshots**
Will provide screenshots later, forgot that changing pages clears the console so it fixed itself

**System Information:**
 - OS: Windows 10
 - Valour Version: Latest (0.0.8.2)
 - Valour Platform: Desktop App

**Comment by Grimtin10** [comment]
i know refreshing can fix it, its just that this should _never_ happen in the first place

**Comment by Grimtin10** [comment]
example
![ftzhdgtxs](https://user-images.githubusercontent.com/20334046/109587507-061df900-7abc-11eb-9d03-1815d0b62bae.gif)

**Comment by Grimtin10** [comment]
still happens in 0.0.8.55

**Comment by superjacobl** [comment]
Does this still happen in a small planet? It may have something to do with the planet member list

**Comment by Coca162** [comment]
This seems like it has gone away, if this occurs again people are welcome to open the issue again
