### ISSUE TITLE
🐛 Bug - no messages

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#216]
**Describe the bug**
yes, i cant see the messages or neither the user list

**To Reproduce**
hard refresh valour

**Expected behavior**
to be as it was

**Screenshots**
![image](https://user-images.githubusercontent.com/72446297/109062616-e7d48980-76c6-11eb-9c77-f3e082b982bc.png)

**System Information:**
 - OS: windows 10
 - Valour Version 0.0.8.4
 - Valour Platform: web
     - Browser: opera gx **Only answer when saying you use Web**

**Additional context**

**Comment by superjacobl** [comment]
this is fixed in #217

**Comment by drop-lt** [comment]
we know
