### ISSUE TITLE
🐛 Bug -issue accessing the app

### ISSUE THREAD

**Issue by Onyourtoes** [Valour-Software/Valour#222]
I dont know if anyone else is having a problem but i cant get on valour rn. Its a bad gateway, here is error report
Ray ID: 627b61bc8ad1187b
Your IP address: Not mentioning
Error reference number: 502
cloudfare Locationg: atlanta
if i can get a comment about why this is happening that would be amazing, i cant seem to get on through my laptop on the website, app, or on my phone

**Comment by Onyourtoes** [comment]
i have restarted my pc and phone, and it still does the same thing

**Comment by SentyFunBall** [comment]
it just means the servers are not online, nothing with you. 502 errors are nothing for you to worry about.

**Comment by fruitcake5** [comment]
Not a bug, servers are down

**Comment by Onyourtoes** [comment]
ok so when should it be back up?

**Comment by drop-lt** [comment]
no one really knows

**Comment by Onyourtoes** [comment]
dang ok. well i hope there up soon, its pretty lonely ngl

**Comment by Onyourtoes** [comment]
Its fixed now
servers are back up
