### ISSUE TITLE
📦 Feature - hackerman mode for Valour

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#226]
**Is your feature request related to a problem? Please describe.**
i think it is good and should be on valour. 

**Describe the solution you'd like**
basically this
![image](https://user-images.githubusercontent.com/72446297/109437866-15426f80-7a06-11eb-90f6-0b1bd9ccc8a7.png)

**Describe alternatives you've considered**
none

**Additional context**
not the base one, like a sencodary theme

**Comment by SpikeViper** [comment]
Themes are planned.
