### ISSUE TITLE
🐛 Bug - Valour is very laggy on cellphone

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#228]
**Describe the bug**
valour starts and all of that, but when i am going to a server, i just cant touch the textbar or else it crashes

**To Reproduce**
1. open valour in mobile
2. enter in a server

**Expected behavior**
just work.

**Screenshots**

**System Information:**
 - OS: android 10
 - Valour Version: 0.0.8.55
 - Valour Platform: pwa, web for mobile
     - Browser: chrome, opera touch **Only answer when saying you use Web**

**Additional context**
cellphone is an m30

**Comment by SentyFunBall** [comment]
its stable on my phone lmao. might just be because i have a powerful phone?

**Comment by drop-lt** [comment]
> its stable on my phone lmao. might just be because i have a powerful phone?

bro,i literally brought this phone january last year

**Comment by SentyFunBall** [comment]
its stable on my iphone se 2, which is also from around the same time.

**Comment by drop-lt** [comment]
and additional info: i had a server thatvis just myself, and it works fine

**Comment by superjacobl** [comment]
this is most likey the user list on the left side

**Comment by superjacobl** [comment]
we will start only displaying like 64 or 128 users in the userlist soon

**Comment by Coca162** [comment]
This seems like it has gone away, if this occurs again people are welcome to open the issue again
