### ISSUE TITLE
🐛 Bug - Valour frequently crashing

### ISSUE THREAD

**Issue by Onyourtoes** [Valour-Software/Valour#236]
**Describe the bug**
Valour has been crashing very frequently lately, and it has been buggy to where you cant change channels. when it starts to crash texts will appear to be doubled up and you wont be able to send anything. i dont know if this is user error or the servers bugging out but it would be nice to get this fixed

**Comment by JimSkywalker** [comment]
could you add some more info like how to replicate or what version you are using?

**Comment by SpikeViper** [comment]
Believe this was due to message key issue which is resolved. Reopen if it's not fixed.
