### ISSUE TITLE
🐛 Bug - valour duplicating messages and crashing

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#238]
**Describe the bug**
Valour crashes after some time that it is idled

**To Reproduce**
1. as far as im aware, you just need to let Valour idle for one hour or two

**Expected behavior**
just work fine and normally

**Screenshots**
![image](https://user-images.githubusercontent.com/72446297/114787536-627c6580-9d56-11eb-9cd0-f8a4c043ef67.png)
![image](https://user-images.githubusercontent.com/72446297/114791092-3c59c400-9d5c-11eb-97cf-6d90f219a89f.png)
![image](https://user-images.githubusercontent.com/72446297/114791237-8f337b80-9d5c-11eb-9310-38ea58e0b47e.png)

if the quality is bad, i can copy/pase the text here or something

**System Information:**
 - OS: Manjaro linux (applies to windows 10 too, tested)
 - Valour Version: this bug is consise since 0.0.6.x i think, but tested on 0.0.8.6
 - Valour Platform: web (applies to mobile, but i cant see console there)
     - Browser: [e.g. chrome, safari] firefox;
**Additional context**

**Comment by SpikeViper** [comment]
Ah our good friend, key collisions. Will try to replicate.

**Comment by drop-lt** [comment]
guess what, it still happens, i think that can be my slow internet that is sending 2 messages at once and basically killing valour
![image](https://user-images.githubusercontent.com/72446297/115088754-49ef8500-9ee7-11eb-93f0-bd5ff4564b9f.png)

**Comment by Onyourtoes** [comment]
sometimes the double messages would assoiciate with valour crashing, i havent seen normal double text besides when the app crashes and makes me reload

**Comment by superjacobl** [comment]
@drop-lt has this happend in the last few days?

**Comment by drop-lt** [comment]
less commonly, like twice a day or so

**Comment by superjacobl** [comment]
I bet it’s something to do with Firefox

**Comment by drop-lt** [comment]
gonna try with Chrome,i will see what happens

**Comment by superjacobl** [comment]
this is fixed
