### ISSUE TITLE
🐛 Bug - Infinite Color Picker Elements

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#246]
**Describe the bug**
Everytime you click on the "Roles" button in the edit planet window, it creates a new color picker element.

**Expected behavior**
That it should delete the prev color picker elements, or  just use the same one.

**Screenshots**

**System Information:**
 - OS: Windows 10
 - Valour Version: 0.0.8.62
 - Valour Platform: Web
     - Browser: Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/16181531/115162009-eabc7c80-a06e-11eb-96f9-7b2b23f2484d.png)

**Comment by SpikeViper** [comment]
Fixed in my dev branch.
