### ISSUE TITLE
📦 Feature - a blank db on the repository

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#248]
**Is your feature request related to a problem? Please describe.**
Not quite a user problem, more like a developer problem to be honest, because we need to make the database for ourselves, but i have literally no idea how it is

**Describe the solution you'd like**
a blank database on the repo, really just for testing and developing over it

**Describe alternatives you've considered**
 a link to a project on [drawSQL](https://drawsql.app/) would help a lot too

**Additional context**
That is literally the only thing that is stopping me and some other devs from contributing more to Valour

**Comment by SentyFunBall** [comment]
i agree

**Comment by Coca162** [comment]
Has been done
