### ISSUE TITLE
🐛 Bug - Color picker makes role menu go bye bye

### ISSUE THREAD

**Issue by SentyFunBall** [Valour-Software/Valour#250]
**Describe the bug**
If you're using the role color picker, and the cursor moves off the picker while still holding LMB, it gets rid of the role menu. 

**To Reproduce**
1. Go to edit a role
2. Click on the button to show the color picker
3. Move your cursor off the menu while holding LMB then release LMB

**Expected behavior**
For it to not get rid of the role menu

**System Information:**
 - OS: Windows 10
 - Valour Version: 0.0.8.63
 - Valour Platform: Web
     - Browser: Chrome

**Comment by SentyFunBall** [comment]
edit: typo

**Comment by superjacobl** [comment]
@SentyFunBall can you test this again? I believe this was fixed in a recent version.

**Comment by SentyFunBall** [comment]
yeah ill just it gimme a min

**Comment by superjacobl** [comment]
Ok

**Comment by SentyFunBall** [comment]
yeah it still seems to happen to me, my valour has been found to be pretty cursed though

**Comment by superjacobl** [comment]
Maybe clear cache?

**Comment by superjacobl** [comment]
Bc this is not happening for me

**Comment by SentyFunBall** [comment]
yeah did ctrl+f5 and cleared cache, still happening

**Comment by JimSkywalker** [comment]
this happens to me too

**Comment by Coca162** [comment]
Can confirm this is still a bug.
![n5HYinplj0](https://user-images.githubusercontent.com/62479942/117197566-deab1b80-addf-11eb-9370-4984c5ce9b15.gif)

**Comment by superjacobl** [comment]
i guess pr #245 did not work

**Comment by SpikeViper** [comment]
It fixed part of the problem. I have a solution in my next push. Need to switch from onclick to onpointerdown so we see the first element touched, not the element when the mouse is in licked.

**Comment by SpikeViper** [comment]
Unclicked smh

**Comment by SpikeViper** [comment]
Fixed in my dev branch.
