### ISSUE TITLE
📦 Feature - move the new chat window button a bit

### ISSUE THREAD

**Issue by JimSkywalker** [Valour-Software/Valour#256]
**Is your feature request related to a problem? Please describe.**
The scroll bar is right next to the new chat window button, so if you let go of the scroll bar next to it you can't grab it as it will just open a new chat window. 
**Describe the solution you'd like**
I would like it if the open new chat window was moved over a bit to the left.

**Describe alternatives you've considered**
It could also be fixed by moving the new chat window button to the banner as it doesn't have much use right now. 
**Additional context**
no additional context

**Comment by drop-lt** [comment]
ok, shouldnt be that hard
