### ISSUE TITLE
🐛 Bug - Landscape Valour does not render properly

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#264]
**Describe the bug**
you can literally the ui with 3 simple steps.

**To Reproduce**
1. Go to mobile
2. Click on valour 
3. Go landscape mode

**Expected behavior**
everything except that

**Screenshots**
![Screenshot_20210505-230737_Chrome.jpg](https://user-images.githubusercontent.com/72446297/117232202-12457000-adf7-11eb-88bc-0fb8ddb3a986.jpg)

**System Information:**
 - OS: android 10
 - Valour Version 0.0.8.7
 - Valour Platform: Mobile app
     - Browser: [e.g. chrome, safari] **Only answer when saying you use Web**

**Additional context**

**Comment by SpikeViper** [comment]
We just need to block landscape mode, honestly.

**Comment by drop-lt** [comment]
> We just need to block landscape mode, honestly.

you should do like whatsapp or something, so the textarea covers the entire screen and you can just cover everything else

**Comment by SpikeViper** [comment]
> you should do like whatsapp or something, so the textarea covers the entire screen and you can just cover everything else

We could.

**Comment by Coca162** [comment]
Reopen if this is still a issue, or make a feature requests for the whatapp-like idea
