### ISSUE TITLE
📦 Feature - Roles Within Roles

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#265]
### Issue:
Just like with categories roles could have the same property of being able to put inside each other. This would be useful for role groups/dividers like Admin, Mod, Government, etc... or for when roles share similar permissions.

### Possible Solution:
Being able to put roles inside other roles just like how categories are. Preferably also displayed clearly once that is added. You could even have everyone role treated like a parent role for all the other roles. 

### Additional context:
I got the idea from what Jambon was saying about role dividers and I think it is pretty nice.

**Comment by SpikeViper** [comment]
Did you hear that? That was my souls crying.

**Comment by Coca162** [comment]
> Did you hear that? That was my soul crying.

Well, I don't know how this idea was not suggested when roles were originally being made! It seems just like the next step from having categories inside categories.

**Comment by JimSkywalker** [comment]
people on discord could have multiple roles at once. I am unsure weather this can be done on valour at the moment but it might be easier

**Comment by Coca162** [comment]
Closed as not planned
