### ISSUE TITLE
🐛 Bug - new roles and new channels only show up after refresh

### ISSUE THREAD

**Issue by JimSkywalker** [Valour-Software/Valour#270]
**Describe the bug**
When I tested stuff on my server, new channels and new roles only showed up after a refresh 
**To Reproduce**
1. create a new role or channel '
2. see that it doesn't show up  
3. refresh valour and re-enter the planet 
4. See role or channel

**Expected behavior**
the role or channel should show up immediately 

**Screenshots**

**System Information:**
 - OS: windows 8.1
 - Valour Version 0.0.8.7
 - Valour Platform: web
     - Browser: chrome 
**Additional context**
The issues that arise are not that severe but it can cause new planet owners to accidentally create a ton of extra roles or channels if they don't know about the bug.

**Comment by superjacobl** [comment]
I am working on a fix for this yesterday, should be done in a few days

**Comment by superjacobl** [comment]
this is fixed
