### ISSUE TITLE
🐛 Bug - <general chat has broken completely>

### ISSUE THREAD

**Issue by JimSkywalker** [Valour-Software/Valour#275]
**Describe the bug**
Messages don't remain in general chat on the valour planet and once you click off you can't click back on
**To Reproduce**
1. Go to the valour planet 
2. Click on off-topic
3. Click on general 
4. it won't be selected 
**Expected behavior**
You should be able to use general chat like any other channel 
**Screenshots**

**System Information:**
 - OS: windows 8.1
 - Valour Version 0.0.8.7 pre-pre alpha 
 - Valour Platform: Web
     - Browser: chrome

**Additional context**
ignore my comment, more and more channels are breaking. you might want to add high severity to this

**Comment by JimSkywalker** [comment]
does not happen on other planets

**Comment by superjacobl** [comment]
This may be related to a key-value issues with blazor, when opening console, it had some error messages about key-value stuff in blazor

**Comment by superjacobl** [comment]
This has been fixed
