### ISSUE TITLE
🏗 Feature - Embeds

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#288]
## Describe Issue
Embeds

## Form Elements

- [x] Button
- [x] Input text box

## Stuff to do

- [x] Make a static embed example with html
- [x] Convert static example to blazor
- [x] Add form elements and stuff
- [x] Have client send all form data for every interaction
- [x] Create server route
- [x] Send interaction to the bot that created the embed using a signalr event
- [x] Embed Pages

**Comment by superjacobl** [comment]
this is done in #299

**Comment by drop-lt** [comment]
deleting the embeds so no chat wall
