### ISSUE TITLE
🐛 Bug - allow markdown size styling in embeds

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#331]
![image](https://user-images.githubusercontent.com/16181531/128621636-1212f64b-462f-448e-8e54-a2f4d7f78b07.png)
this line resets the font-size

**Comment by SpikeViper** [comment]
I feel like you could have fixed this with as much effort as it took to make this an issue.

**Comment by superjacobl** [comment]
i did not know that you checked github imao

**Comment by superjacobl** [comment]
and no it would require more work, as i would have to check if the item contains a markdown size hashtag

**Comment by SpikeViper** [comment]
I get email notifications!

**Comment by superjacobl** [comment]
me too!

**Comment by superjacobl** [comment]
quite annoying

**Comment by superjacobl** [comment]
This has been fixed
