### ISSUE TITLE
🏗 Feature - Have a "grid" option for embeds

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#338]
This would put the elements of a embed into a grid format. Default would be false.

**Comment by drop-lt** [comment]
something like this:
```js
"grid": {
    "enabled": true,
    "rows": 16, // if parent
    "columns: 32,
    "at_row": 1, // if children
    "at_column": 2
}
```
btw it would be nice if it could go inside of each other

**Comment by superjacobl** [comment]
never even thought about having custom grid settings, will add!

**Comment by superjacobl** [comment]
This can be done using rows, no need for columns
