### ISSUE TITLE
📦 Feature - Indication of Unread Messages

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#339]
It is currently impossible to tell if a channel contains messages that have not been read before without opening the channel.

## Solution

Fill in the message icon when a channel has newly sent messages in it. Should update when messages are viewed on any other client.

**Comment by superjacobl** [comment]
this is planned

**Comment by superjacobl** [comment]
this requires #464 to be done

**Comment by Coca162** [comment]
This does not require #464 to be done as messages could be new in the past 24 hours

**Comment by Coca162** [comment]
An extension to this issue would be to fill the channel icon white for unread messages, red for mentions and blue for role mentions. Although these might be spun off into their own issues later on.
