### ISSUE TITLE
🐛 Bug - Banning/Kicking yourself in your own planet results in a crash

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#342]
If you are on your own planet banning or kicking yourself will result in the whole of valour crashing!

## **To Reproduce**
# WARNING! DO NOT REPRODUCE ON PRODUCTION VALOUR!
1. Go on your own planet
2. Right-click yourself
3. Click on either ban or kick

## **Expected behavior**
For banning/kicking yourself to not be possible!

**Comment by JimSkywalker** [comment]
that's interesting, when I tried to do it before i saw this  because i couldn't find any other way to leave a server, nothing happened.

**Comment by Coca162** [comment]
This is no longer an issue but the UI for ban and kick should be removed from yourself
