### ISSUE TITLE
🐛 Bug - Opening 3 chat windows breaks pinging and message ghosts

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#345]
**Describe the bug**
Opening 3 chat windows breaks pinging and message ghosts

**To Reproduce**
1. Open 3 chat windows
2. type a message
3. see no ghost
4. try pinging
5. see no ping window

**Comment by Coca162** [comment]
Pinging is no longer an issue however ghosts can be seen in the incorrect chat window, a separate issue will be made for this
