### ISSUE TITLE
🐛 Bug - ping selection window does not appear if theres not a space in front of it

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#350]
**Describe the bug**
ping selection window does not appear if theres not a space in front of it.

**To Reproduce**
1. Type something like "test:"
2. Type the @ symbol
3. See bug

**Expected behavior**
the ping selection window should always appear if there is a @ symbol.

**System Information:**
 - OS: Windows 10
 - Valour Version 0.0.9.1
 - Valour Platform: Web
     - Browser: Chrome

**Comment by Coca162** [comment]
@SpikeViper should this be considered a bug?

**Comment by SpikeViper** [comment]
This is standard behavior on other platforms
