### ISSUE TITLE
🐛 Bug - Logout button doesnt work

### ISSUE THREAD

**Issue by Onyourtoes** [Valour-Software/Valour#352]
**Describe the bug**
Logout button doesnt work, k was trying to test and see if it worked, along with see if i could fix my account, wondering when we are going to get this to work?

**Expected behavior**
expected it to log me out

**System Information:**
 - Valour Version 0.0.8.7
 - Valour Platform: Website
     - Browser: Chrome

**Comment by superjacobl** [comment]
the current valour version is 0.0.9.1. Try refershing your page more than once, and try doing control f5

**Comment by Onyourtoes** [comment]
ah that must be it, doesnt seem to update sadly

**Comment by superjacobl** [comment]
this is fixed
