### ISSUE TITLE
🏗 Feature - Planet Rollback

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#355]
## Describe Issue
Allow the owners of a planet to roleback changes (like channel/role edits) from the last 24 hours (could be made longer).

Note: we should not do this for at least a few months, as many other features are much more important.

## Checklist
Add this later

**Comment by SpikeViper** [comment]
This is honestly unrealistic. Many changes to planets come in the form of user actions, such as joining and leaving, message edits (where we won't be saving originals for privacy reasons) among a thousand other issues with this. We can't force re-join kicked users or users who chose to leave, and recovering deleted messages is a big no-no.

**Comment by superjacobl** [comment]
sure, but for things like editing channels, moving them, role changes can be rollbacked

**Comment by SpikeViper** [comment]
Seems unnecessary. And complicated.

**Comment by fruitcake5** [comment]
rollback* heh

**Comment by Coca162** [comment]
If this were to be made it would have to be after #303 as you could roll back to a previous version of the JSON

**Comment by SpikeViper** [comment]
Closing as "not a feature I think is a good idea"
