### ISSUE TITLE
🐛 Bug - Scrolling up causes scrolling forever

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#377]
**Describe the bug**
Scrolling up to get new messages results in a chat window causes it to keep scrolling up forever

**To Reproduce**
1. Open channel
2. Scroll up
3. See error

**System Information:**
 - OS: Windows 10
 - Valour Version 0.1.0.2
 - Valour Platform: Web
     - Browser: Chrome

**Comment by Coca162** [comment]
The bug is old and cannot be replicated
