### ISSUE TITLE
🐛 Bug - HTTP Status code instead of error message on unverified account

### ISSUE THREAD

**Issue by AliceDTRH** [Valour-Software/Valour#388]
**Describe the bug**
The error messages during login are not sent, instead, the HTTP Status code is shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Register a new account
2. Try to log in without verifying

**Expected behaviour**
An error message that explains to me why the login failed.

**What I see instead**
`Failed to request user. Error code Forbidden`

**Screenshots**

**System Information:**
I'm using the current live version on [valour.gg](https://valour.gg/)
OS and browser are not relevant

**Additional context**
https://github.com/Vooper-Media-LLC/Valour/blob/03811746eefe08e3f6f98897bed2887cb2631b23/Valour/Client/Shared/Utility/LoginComponent.razor#L81
`response.StatusCode.ToString()` should be `message`.

I would make a PR but I have no experience with Razor and `message` probably needs to be sanitized.

**Comment by Coca162** [comment]
No longer a issue
