### ISSUE TITLE
Web client does not "clip" unicode glyphs

### ISSUE THREAD

**Issue by idi-moe** [Valour-Software/Valour#39]
Image below. When rendering unicode glyphs with the addon things, they don't get clipped to be only one line long, they extend fully.

![image](https://user-images.githubusercontent.com/70919760/106347391-15771000-628c-11eb-94d5-50ad6c234689.png)

![image](https://user-images.githubusercontent.com/70919760/106347378-efea0680-628b-11eb-9cfb-768234d67551.png)

**Comment by SpikeViper** [comment]
This is closed
