### ISSUE TITLE
🐛 Bug - Cant put cyrillic text as the name of a planet

### ISSUE THREAD

**Issue by YahooCar** [Valour-Software/Valour#408]
**Describe the bug**
Cant put cyrillic text as the name of a planet

**To Reproduce**
1. Click on Create planet
2. input any cyrillic text
3. press submit
4. You get an error saying "Created planet, but error occured retrieving. Please restart Valour."

**Expected behavior**
I expected the new planet to be in my planets list and to be able to use the planet to chat.

**System Information:**
 - OS: Windows 11
 - Valour Version: 0.1.2.2
 - Valour Platform: Web
     - Browser: Edge/Chromium

**Comment by kiwiscripter** [comment]
@superjacobl

**Comment by Coca162** [comment]
This will not be fixed unless @SpikeViper thinks that allowing other Unicode chars is a good idea
