### ISSUE TITLE
Randomly drops connection to server.

### ISSUE THREAD

**Issue by SentyFunBall** [Valour-Software/Valour#42]
I randomly drop connection, being unable to get new messages from other users, but i can still send messages. Yes i tried scrolling down. pressing F5 fixes the issue temporarily.

Says this error when it drops connection:
![image](https://user-images.githubusercontent.com/57205125/106366786-26a73780-62f3-11eb-91de-a2c81cf8e1d9.png)

And these errors at intervals: 
![image](https://user-images.githubusercontent.com/57205125/106366767-15f6c180-62f3-11eb-9c6a-9fc89e6c1aea.png)

**Comment by SpikeViper** [comment]
This has been resolved (hopefully)

**Comment by SentyFunBall** [comment]
> This has been resolved (hopefully)

Not for me, it still forces me to press ctrl+f5 every minute or so, and wont let me see messages.
