### ISSUE TITLE
Username does not accept numbers

### ISSUE THREAD

**Issue by Olirules10** [Valour-Software/Valour#43]
You cannot use any numbers in your username even though it asks for alphanumerical usernames. I have tried both with and without a capital letter so it is not that which is causing the issue.

![EFAE85BB-A80C-4B20-8CE6-FFA688EA9A35](https://user-images.githubusercontent.com/70974222/106367648-15364d80-633c-11eb-920f-c04020640655.jpeg)

**Comment by superjacobl** [comment]
i belive this is a issue with phone keyboard putting a whilespace after the username

**Comment by SpikeViper** [comment]
Fixed in 1985c4f250a319a6a2c8e59f0a918186a9befb23
