### ISSUE TITLE
Verification Email Doesn't Send

### ISSUE THREAD

**Issue by Olirules10** [Valour-Software/Valour#47]
When making a new account the verification email doesn't send, there is also no option to resend it, so that should be added. You can also not remake an account witht that same email or delete that account that is using that email, so you are stuck not using that email ever. I am also running out of email accounts so help.

![image](https://user-images.githubusercontent.com/70974222/106369547-651c1100-634a-11eb-90f4-1a88721c9f90.png)

**Comment by charmich0802** [comment]
it didnt ask to confirm mine it just let me in without confirming

**Comment by Olirules10** [comment]
> it didnt ask to confirm mine it just let me in without confirming

I have tried this, however that is another bug that should also be fixed

**Comment by fruitcake5** [comment]
> it didnt ask to confirm mine it just let me in without confirming

thats concerning

**Comment by charmich0802** [comment]
> > it didnt ask to confirm mine it just let me in without confirming
> 
> thats concerning

it might have had something to do with spike fixing my account after kicking me out of the account creation menu and not letting me use my username again

**Comment by Olirules10** [comment]
> > > it didnt ask to confirm mine it just let me in without confirming
> > 
> > 
> > thats concerning
> 
> it might have had something to do with spike fixing my account after kicking me out of the account creation menu and not letting me use my username again

Hopefully, good thing to check though

**Comment by charmich0802** [comment]
> > > > it didnt ask to confirm mine it just let me in without confirming
> > > 
> > > 
> > > thats concerning
> > 
> > 
> > it might have had something to do with spike fixing my account after kicking me out of the account creation menu and not letting me use my username again
> 
> Hopefully, good thing to check though

yeah

**Comment by SpikeViper** [comment]
This was me changing the DB manually to fix their account. The base not sending is still an issue, but there is no security flaw.

**Comment by brndnln** [comment]
> This was me changing the DB manually to fix their account. The base not sending is still an issue, but there is no security flaw.
Does this mean I can close #48?

**Comment by SpikeViper** [comment]
Yes. Furthermore, this should be fixed. Emails with a trailing whitespace were not being sanitized properly.

**Comment by fruitcake5** [comment]
If you can't use your account because of this, tell me your username/user ID and I can fix it for you
