### ISSUE TITLE
When you have 3 chat channels open at the same time, your message in two of the channels get copied three times

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#506]

**Comment by Coca162** [comment]
Please add screenshots and instructions on how to replicate @superjacobl as it is quite hard to understand

**Comment by superjacobl** [comment]
![image](https://user-images.githubusercontent.com/16181531/179454914-41ac9395-747c-4272-a880-753b201b0b2c.png)

**Comment by SpikeViper** [comment]
Should be fixed in new window system
