### ISSUE TITLE
🐛 Bug - Switching channels glitch

### ISSUE THREAD

**Issue by Ryguy6001** [Valour-Software/Valour#535]
You stay in the same channel when you try to switch several times.
https://user-images.githubusercontent.com/72236069/179414138-eeff1889-432a-476b-9f0f-73f756d1dadd.MOV

IOS version 15.5 and added it to home screen.

**Comment by Coca162** [comment]
This can be replicated on PC if you click spam click multiple channels

**Comment by SpikeViper** [comment]
Needs testing with new window system

**Comment by Ryguy6001** [comment]
> Needs testing with new window system

K

**Comment by Ryguy6001** [comment]
https://user-images.githubusercontent.com/72236069/180616160-6b45fafc-3a1e-4327-a283-c67ea18f1bb3.MOV
@SpikeViper Here it is on the new window system

**Comment by Coca162** [comment]
I think a bug similar to the previous one now exists with the id system so this issue can be still kept open

**Comment by intothenextportal** [comment]
this happened to me on pc and now i cant send messages or at least the channel wont update for me

**Comment by SpikeViper** [comment]
I believe this is now resolved
