### ISSUE TITLE
🐛 Bug - Third channel window ghost message in wrong window

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#554]
**Describe the bug**
Ghost messages are in the incorrect window when you use the 3rd channel window

**To Reproduce**
Steps to reproduce the behaviour:
1. Open 3 channel windows
2. Type a message in the 3rd channel on the bottom right
3. Ghost message shows up in 2nd channel on the top right

**Expected behaviour**
For it to go in the 3rd channel

**Screenshots**
![image](https://user-images.githubusercontent.com/62479942/179450506-74cf5b27-38f7-4d18-aebc-90b743c23837.png)

**System Information:**
 - Valour Version 0.1.3.2 Pre-Alpha

**Comment by Coca162** [comment]
To note it is not just ghosting, it is sending the messages in that channel (if it is a different one) and also not scrolling down the 3rd channel

**Comment by SpikeViper** [comment]
New window system should have resolved this
