### ISSUE TITLE
🐛 Bug - Mentions Menu does not update for new members

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#574]
**To Reproduce**
1. Have two different accounts available
2. Have one account on a planet's channel
3. Invite another account to planet
4. Try to ping the newly joined account from the first account

**Expected behaviour**
User to be automatically added to the mentions list

**System Information:**
 - Valour Version 0.1.7.5 Pre-Alpha

**Comment by SpikeViper** [comment]
Fixed in 0.2.1.0
