### ISSUE TITLE
Message Limits

### ISSUE THREAD

**Issue by identithree** [Valour-Software/Valour#59]
can someone make a issue, where we will have a 4k default limit and make a flag in Planet.cs to allow admins to set limit?

_Originally posted by @superjacobl in https://github.com/SpikeViper/Valour/issues/58#issuecomment-770434436_

**Comment by AidenWilkins** [comment]
Will they be allowed to have greater than 4k or is it that max?

**Comment by superjacobl** [comment]
Added a temp limit for right now
