### ISSUE TITLE
Prevent whitespace in email input

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#63]
2 mins ago, email authenticated.

![86d83b7f-b0ef-4882-845d-1f753da8cac1](https://user-images.githubusercontent.com/72446297/106396081-87626d00-63e4-11eb-871c-2e11db8f4475.jpg)
![image](https://user-images.githubusercontent.com/72446297/106396297-ca711000-63e5-11eb-90d5-136c7fb8b2af.png)
(its in portuguese because i speak portuguese)

**Comment by brndnln** [comment]
Did you use the one time password?

**Comment by drop-lt** [comment]
yesterday

**Comment by brndnln** [comment]
Oh, I think it is because @SpikeViper dropped all users as it was temporary (maybe).

**Comment by fruitcake5** [comment]
This was due to whitespace being permitted in the input
