### ISSUE TITLE
🐛 Bug - Pasting becomes duplicated with multiple chat windows

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#640]
Two chat channels result in pasting logic being repeated

**To Reproduce**
1. Open two chat channel windows
2. Type "DUPLICATE"
3. Observe "DUPLICATEDUPLICATE"

**Additional Notes**
Something weird happens if you copy & paste a message when you have two channels open. It get pasted 3 times??? Best to investigate after fixing this bug to see if it is still an issue.

**System Information:**
 - Valour Version 0.1.3.3 Pre-Alpha

**Comment by SpikeViper** [comment]
Fixed
