### ISSUE TITLE
🐛 Bug - Issue when logging in with IOS

### ISSUE THREAD

**Issue by intothenextportal** [Valour-Software/Valour#659]
**Describe the bug**
So im on ios version 15.5 and when i open the main valour planet it looks like this
<img src="https://user-images.githubusercontent.com/81200460/181276745-d3d1977e-8e02-4b07-871d-813199c8de83.png" width="250" >
Now i have scrolled all the way down and the text box is nowhere, sometimes its there and sometimes its not example <img src="https://user-images.githubusercontent.com/81200460/181277013-fe7715ed-35f8-499d-a249-74e1d21b29d3.png" width="250">
I logged in again and the text box appeared i have no clue what causes this or why it only works half the time.

**Comment by SpikeViper** [comment]
This should be fixed now
