### ISSUE TITLE
Move "Add Chat Window" Button on Mobile

### ISSUE THREAD

**Issue by identithree** [Valour-Software/Valour#67]
On phone the add a chat window is in the top left corner and it would be nice to move it to top right.

_Originally posted by @Ryguy6001 in https://github.com/SpikeViper/Valour/discussions/66_

**Comment by SpikeViper** [comment]
This is more of a result of us not supporting mobile yet

**Comment by brndnln** [comment]
As this is still a problem, however not one we are taking at this time, I will reopen the issue, add the `Won't Fix` label, and lock and limit conversation to collaborators.

**Comment by brndnln** [comment]
This might work now that mobile support is here

**Comment by brndnln** [comment]
This works now.
