### ISSUE TITLE
🐛 Bug - dots will need to count

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#70]
gmail doesn't care about dots "." in the address, so:
myemail@gmail.com

and

m.y.e.m.a.i.l@gmail.com

are the same person, but with different addresses

that could cause a lot of bypasses, as such:
server / email  ban bypass using the same email, because a "different" email is being used, but is the same person

if the dots are ignored, email ban could be an very useful tool, but just for people that are authorized to do so

**Comment by brndnln** [comment]
Please submit a new issue and follow the issue template please.
