### ISSUE TITLE
🐛 Bug - Access to planet data without token

### ISSUE THREAD

**Issue by fruitcake5** [Valour-Software/Valour#72]
**Describe the bug**
Data for planets is accessible without a token in the URL, making the data open to everyone

**To Reproduce**
1. Go to https://valour.gg/Planet/GetPlanet?planet_id=69

**Expected behavior**
Should be given a 401 Unauthorized

**Comment by JimSkywalker** [comment]
i followed your instructions and all i got was sorry there is nothing here

**Comment by fruitcake5** [comment]
probably fixed and not closed

**Comment by superjacobl** [comment]
This is fixed
