### ISSUE TITLE
🐛 Bug - Access to planet user data without being in the planet

### ISSUE THREAD

**Issue by fruitcake5** [Valour-Software/Valour#73]
**Describe the bug**
Title

**To Reproduce**
1. Go to `https://valour.gg/User/GetPlanetUsers?Planet_Id=69&token=<VALID TOKEN>&userid=<VALID USERID>`

**Expected behavior**
403 Forbidden

**Comment by Olirules10** [comment]
Why is a 403 error needed? It doesn't show any user data?
![image](https://user-images.githubusercontent.com/70974222/106587411-8004a600-6541-11eb-9786-7c8ba8244c2a.png)

**Comment by fruitcake5** [comment]
I assume it got fixed..?

**Comment by Olirules10** [comment]
yeah idk
