### ISSUE TITLE
🐛 Bug - Duplication of members in mention list

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#731]
When someone attempts to @ a member some members are seen multiple times

**Screenshots**
![image](https://user-images.githubusercontent.com/62479942/183712438-e9513fed-1d0a-4144-a519-3e1d0f8183f6.png)
![image](https://user-images.githubusercontent.com/62479942/183712461-3414c302-1a4a-4bfa-a00e-9cac7aa573a8.png)

Valour Version 0.1.3.4 Pre-Alpha

**Comment by SpikeViper** [comment]
Fixed
