### ISSUE TITLE
📦 Feature (for github) - classifying issues in title

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#74]
**Is your feature request related to a problem? Please describe.**
title

**Describe the solution you'd like**
every element in parenthesis, issue/ feature in square brackets.

**Describe alternatives you've considered**
something like:
(css) [issue] outline in text area is strange
(css) [feature] add an transition to the image hovering
(connection) [issue] reloading while raid was really slow.
(general) [feature] add an "slow internet" mode like gmail

**Comment by brndnln** [comment]
It might be interesting, however we could accomplish the same thing with labels and not sacrifice with titles.

**Comment by drop-lt** [comment]
so no? i thought that because it would make easier to read though issues by the title, because the labels are automatized

**Comment by brndnln** [comment]
You can add a label when you create an issue.

**Comment by drop-lt** [comment]
i didnt saw it like 12 times....

**Comment by brndnln** [comment]
As this issue is dormant and not getting attention, I will close the issue but not lock it. If anyone has further comment, please reopen this issue.
