### ISSUE TITLE
🐛 Bug - Can't swap between text channels

### ISSUE THREAD

**Issue by TurtleWasTaken** [Valour-Software/Valour#75]
I can't swap between text channels

**To Reproduce**
1) Click on a channel
2) Click on another channel

**Expected behavior**
Should swap channel

**Screenshots**
![image](https://user-images.githubusercontent.com/62259727/106442924-d0adcd80-6473-11eb-9866-fe83bef96e53.png)
![image](https://user-images.githubusercontent.com/62259727/106442955-d9060880-6473-11eb-93d2-afb066ae7f57.png)

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web
     - Browser: [e.g. chrome, safari] Google Chrome

**Comment by brndnln** [comment]
That doesn't look good. I would put this as medium severity.
@SpikeViper @fruitcake5 any ideas?

**Comment by superjacobl** [comment]
This has been happening for like 2-3 days now.

**Comment by superjacobl** [comment]
I belive the message components’s keys are colliding. I don’t know if spike fixed the key colliding issue.

**Comment by brndnln** [comment]
For the sake of conformity, I have changed the issue name.

**Comment by superjacobl** [comment]
This has been fixed.
