### ISSUE TITLE
🐛 Bug - restarting valour page says that it is unsafe

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#79]
**Describe the bug**
title

**To Reproduce**
1. go to 'valour.gg'.

**Expected behavior**
go to valour front page.

**Screenshots**
![image](https://user-images.githubusercontent.com/72446297/106492996-598a3080-6497-11eb-8f6d-da127ec8e794.png)
"translates to:"
your connection isn't private
Invaders could be trying to steal your data in valour.gg.

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web
     - Browser: Opera/opera gx

**Additional context**
none

**Comment by brndnln** [comment]
@fruitcake5 Fix SSL please

**Comment by drop-lt** [comment]
guys its working now! probably the browser instance was with some problems
