### ISSUE TITLE
Replying to messages

### ISSUE THREAD

**Issue by identithree** [Valour-Software/Valour#80]
# Board Feature Request
This is a developer feature request (Meant for boards)

## Describe Issue
Allow people to reply to messages (kind of like how discord does it)

## Checklist
Will be in a separate message by @superjacobl

**Comment by superjacobl** [comment]
examples
![image](https://user-images.githubusercontent.com/16181531/126026188-2ddb8da0-efb4-440d-878e-f80dbfaf6a20.png)
![image](https://user-images.githubusercontent.com/16181531/126026195-f29132fa-82db-4729-bd5d-80f531af0247.png)

**Comment by Coca162** [comment]
Images and embeds that are shown in replies should be hidden when the reply is close enough to the message
