### ISSUE TITLE
🐛 Bug - <title for bug report here>

### ISSUE THREAD

**Issue by intothenextportal** [Valour-Software/Valour#818]
![image](https://user-images.githubusercontent.com/81200460/195149256-bc4e3eb0-9e34-4da5-a58f-2ce648b133d8.png)
yeah so basically when closing the first "tab" thats in a different server it for some some reason shows the members list of that server and overlays the names, the only tab i have open is for my server mars

**Comment by Coca162** [comment]
Can't replicate
