### ISSUE TITLE
🐛 Bug - i think i found when name bug starts

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#83]
**Describe the bug**
title

**To Reproduce**
imagine that this conversation whas going:

p11: imagine living in duck continent lol  
p12: noooo, duck continent good.  
p21: imagine living  
p22: yes  

as soon as something hits a limit (idk what or why) here it comes, the bug name:

p11(actually p12): why im p11?
p12(atually p22): (cursing ppl)
p21(acutally other person): lag?
p22:(probably me): lag goes brr (last seen 3 years ago because lag) 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (no screenshots)

**System Information:**
 - OS: windows 10
 - Valour Platform: web
     - Browser: opera gx  **Only answer when saying you use Web**

**Additional context**
probably there is something that is crashing everytime there is a lot of messages (i dont know why the raid didnt crash)
this is just my idea, im probably wrong

**Comment by SpikeViper** [comment]
Name bug *appears* to be resolved
