### ISSUE TITLE
🐛 Bug first name weird

### ISSUE THREAD

**Issue by intothenextportal** [Valour-Software/Valour#836]
![image](https://user-images.githubusercontent.com/81200460/196861648-07d69f31-d81f-45d1-bb2a-968e951dba05.png)
![image](https://user-images.githubusercontent.com/81200460/196861710-54769e2a-84f2-4a88-80e1-4e09b0a7501a.png)
the first person to show in the online list is always grimtin10

**Comment by SpikeViper** [comment]
This should be fixed (check for me)

**Comment by Coca162** [comment]
Can't replicated, reopen if it comes up again
