### ISSUE TITLE
Friend Requests do not update live

### ISSUE THREAD

**Issue by superjacobl** [Valour-Software/Valour#838]
New friend requests do not show up till you reload Valour nor do accepted ones show up until you reload Valour

**Comment by SpikeViper** [comment]
Huh? They should?

**Comment by SpikeViper** [comment]
Oh, unless you mean *other* people accepting them

**Comment by SpikeViper** [comment]
Should probably also send a notification (with a setting for that)

**Comment by superjacobl** [comment]
yeah

**Comment by Coca162** [comment]
Still able to replicate

**Comment by SpikeViper** [comment]
This has been fixed finally
