### ISSUE TITLE
🐛 Bug - Console freaks out page formatting

### ISSUE THREAD

**Issue by notdroplt** [Valour-Software/Valour#916]
**Describe the bug**
when i open the console using the app the whole design is pushed up, also a whole world of console errors show up

**To Reproduce**
1. Open Valour
2. Open Console
3. See error

**Expected behavior**
Design not dying and not that amount of errors

**Screenshots**
![image](https://user-images.githubusercontent.com/117052412/205189968-457430f9-57ca-4d9d-b113-4a77260c51f4.png)
![image](https://user-images.githubusercontent.com/117052412/205190051-e5f0e640-b2b2-4f4c-a32a-6bfc098eb849.png)
![image(1)](https://user-images.githubusercontent.com/117052412/205190122-a258fef8-4fbe-4bcd-b6bf-bb507c1e9778.png)

**System Information:**
 - OS: Arch Linux 64 bits
 - Valour Version:  0.1.6.21
 - Valour Platform: Web
     - Browser: Firefox

**Additional context**
Also, images with very specific aspect ratios and sizes such as the second one cause a massive padding in the image
![image](https://user-images.githubusercontent.com/117052412/205190385-ecbcb615-81ea-4231-b318-dd8df9f12b71.png)

**Comment by notdroplt** [comment]
another thing to point out, when one server delays to load, if i click on a DM it loads "both" at the same time
![image](https://user-images.githubusercontent.com/117052412/205190921-554a2b0d-9cee-4948-b0ca-0f8d6137d184.png)

**Comment by Coca162** [comment]
Unable to replicate on firefox 114.0.2 and Valour 0.2.0.1, closing
