### ISSUE TITLE
🐛 Bug - Table borders

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#94]
**Is your feature request related to a problem? Please describe.**
its very cursed the md tables not having borders

**Describe the solution you'd like**
every time a table is made, for exemple:
```
| valour   |      is     |  Poggers |
|----------|:-------------:|------:|
| change |  my | mind |
```
insted of:

![image](https://user-images.githubusercontent.com/72446297/106537789-cfaf8700-64d9-11eb-8da2-2b7935cb968e.png)

**Describe alternatives you've considered**
should be:
| valour   |      is     |  Poggers |
|----------|:-------------:|------:|
| change |  my | mind |

**Additional context**
Add any other context or screenshots about the feature request here: none

**Comment by brndnln** [comment]
Just to let you know, this is more of a bug then a feature request

**Comment by drop-lt** [comment]
i think is a feature, because the box is already working and is something _to add to_ Valour

**Comment by brndnln** [comment]
No, as the separators should be shown and they are not.

**Comment by drop-lt** [comment]
and its done now
