### ISSUE TITLE
🐛 Bug - <slide to the void>

### ISSUE THREAD

**Issue by ghost** [Valour-Software/Valour#97]
**Describe the bug**
you can go to the void while typing

**To Reproduce**
1. pwa valour
2. go to any chat
3. start to type
4. but slide down to the left

**Expected behavior**
nothing should happen / text should go down

**Screenshots**
![Screenshot_20210201-225015_Chrome.jpg](https://user-images.githubusercontent.com/72446297/106541286-8adb1e80-64e0-11eb-909a-a89d4ca95871.jpg)

**System Information:**
 - OS: android 10
 - Valour Platform: pwa'd valour for cellphone
  

**Additional context**
cellphone: samsung m30

**Comment by brndnln** [comment]
This is still due to the fact that Valour does not have phone support at the current moment.

**Comment by brndnln** [comment]
This might work now that there is mobile support

**Comment by brndnln** [comment]
On a Motorola Moto Z3, this is fixed. Please reopen this issue if you still have problems.
