### ISSUE TITLE
🐛 Bug - Markdown Footnotes

### ISSUE THREAD

**Issue by Coca162** [Valour-Software/Valour#98]
**Describe the bug**
Footnotes do not work with the messaging system of Valour

**To Reproduce**
1. Go to valour.gg
2. type:
```md
Here's a sentence with a footnote. [^1]

[^1]: This is the footnote.
```

**Expected behavior**
Footnote to go to the footnote but instead does nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/62479942/106541415-f1b90180-64f9-11eb-9e50-75702a8d6b19.png)

**System Information:**
 - OS: Win 10
 - Valour Platform: Web
     - Browser: Chrome

**Comment by brndnln** [comment]
This will actually open a new tab. Still needs fixing

**Comment by superjacobl** [comment]
@Coca162 is this fixed yet?

**Comment by Coca162** [comment]
Idk why this was fixed but it was
